# Generated by Django 6.0.3 on 2026-04-05 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detected_by', models.CharField(blank=True, max_length=255)),
                ('data_compromised', models.BooleanField(default=False)),
                ('data_classification', models.CharField(blank=True, choices=[('PII', 'PII'), ('PHI', 'PHI'), ('CONFIDENTIAL', 'Confidential'), ('PUBLIC', 'Public')], max_length=20)),
                ('downtime_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('business_impact', models.TextField(blank=True)),
                ('cve_number', models.CharField(blank=True, max_length=20)),
                ('repeat_incident', models.BooleanField(default=False)),
                ('attack_vector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logger.attackvector')),
                ('incident_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logger.incidenttype')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to='logger.responder')),
            ],
        ),
        migrations.CreateModel(
            name='AffectedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('asset_type', models.CharField(blank=True, choices=[('SERVER', 'Server'), ('WORKSTATION', 'Workstation'), ('MOBILE', 'Mobile'), ('CLOUD', 'Cloud Resource'), ('OTHER', 'Other')], max_length=20)),
                ('owner_department', models.CharField(blank=True, max_length=100)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='logger.incident')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorOfCompromise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ioc_type', models.CharField(choices=[('IP', 'IP Address'), ('DOMAIN', 'Domain'), ('FILE_HASH', 'File Hash'), ('URL', 'URL'), ('EMAIL', 'Email Address')], max_length=20)),
                ('ioc_value', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iocs', to='logger.incident')),
            ],
        ),
        migrations.CreateModel(
            name='MitreMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tactic', models.CharField(max_length=100)),
                ('technique_id', models.CharField(max_length=20)),
                ('technique_name', models.CharField(max_length=150)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitre_mappings', to='logger.incident')),
            ],
        ),
        migrations.CreateModel(
            name='PostIncidentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_cause', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('followup_actions', models.TextField(blank=True)),
                ('authored_at', models.DateTimeField(blank=True, null=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_incident_review', to='logger.incident')),
                ('authored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logger.responder')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('LOG', 'Log File'), ('SCREENSHOT', 'Screenshot'), ('FILE', 'File / Artifact'), ('NOTE', 'Written Note')], max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('chain_of_custody_notes', models.TextField(blank=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='logger.incident')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logger.responder')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('CONTAINMENT', 'Containment'), ('ERADICATION', 'Eradication'), ('RECOVERY', 'Recovery')], max_length=20)),
                ('action_taken', models.TextField()),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_actions', to='logger.incident')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logger.responder')),
            ],
        ),
    ]
