# Generated by Django 6.0.3 on 2026-04-05 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_alter_responder_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('resolution', models.TextField()),
                ('authored_at', models.DateTimeField(auto_now_add=True)),
                ('authored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logger.responder')),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closing_note', to='logger.incident')),
            ],
        ),
    ]
