# Generated by Django 6.0.3 on 2026-04-06 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0005_alter_affectedasset_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affectedasset',
            options={'verbose_name': 'Affected Assets', 'verbose_name_plural': 'Asset History'},
        ),
        migrations.AlterModelOptions(
            name='attackvector',
            options={'verbose_name': 'Attack Vector', 'verbose_name_plural': 'Attack Vector Management'},
        ),
        migrations.AlterModelOptions(
            name='evidence',
            options={'verbose_name': 'Evidence', 'verbose_name_plural': 'Evidence Management'},
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'verbose_name': 'Incidents', 'verbose_name_plural': 'Incident Assignment Management'},
        ),
        migrations.AlterModelOptions(
            name='incidenttype',
            options={'verbose_name': 'Incident Type', 'verbose_name_plural': 'Incident Type Management'},
        ),
        migrations.AlterModelOptions(
            name='indicatorofcompromise',
            options={'verbose_name': 'I.O.C Management', 'verbose_name_plural': 'I.O.C Management'},
        ),
        migrations.AlterModelOptions(
            name='postincidentreview',
            options={'verbose_name': 'Post Incident Review', 'verbose_name_plural': 'Post Incident Review'},
        ),
        migrations.AlterModelOptions(
            name='responder',
            options={'verbose_name': 'Responder   ', 'verbose_name_plural': 'Responder Management'},
        ),
    ]
